version: '3.7'

services:
  web:
    build:
      context: .
      target: development
      restart: true
    command: deno run -A src/serve.ts
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
